"""add job_titles, keywords and job_titles_to_keywords tables

Revision ID: 480d6af579f7
Revises: a25394aed007
Create Date: 2026-03-30 16:42:19.433152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480d6af579f7'
down_revision = 'a25394aed007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('keyword_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_type_id'], ['keyword_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keywords_keyword_type_id'), ['keyword_type_id'], unique=False)

    op.create_table('job_titles_to_keywords',
    sa.Column('job_title_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_titles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_title_id', 'keyword_id')
    )
    # ### end Alembic commands ###

def downgrade():
    op.drop_table('job_titles_to_keywords')
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        # 1. Drop the foreign key constraint first
        batch_op.drop_constraint('keywords_ibfk_1', type_='foreignkey')
        # 2. Then drop the index
        batch_op.drop_index(batch_op.f('ix_keywords_keyword_type_id'))
    op.drop_table('keywords')
    op.drop_table('job_titles')