"""changed name columns

Revision ID: 935fa9bdd978
Revises: 480d6af579f7
Create Date: 2026-03-30 21:24:57.708129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '935fa9bdd978'
down_revision = '480d6af579f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_titles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.drop_column('title')

    with op.batch_alter_table('keyword_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('name')

    with op.batch_alter_table('job_titles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
